# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(450, 600)
        self.widget = QtWidgets.QWidget(LoginWindow)
        self.widget.setGeometry(QtCore.QRect(30, 30, 400, 550))
        self.widget.setStyleSheet("QPushButton#logButton {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(230, 80, 100, 230), stop:1 rgba(180, 0, 110, 230));\n"
"color:rgba(255,255,255,210);\n"
"border:1px solid rgba(150,0,85,255);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#logButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(250, 100, 120, 230), stop:1 rgba(200, 20, 130, 230));\n"
"}\n"
"QPushButton#logButton:pressed {\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QCheckBox#remCheckBox:hover{\n"
"background-color:rgba(0,0,0,0);\n"
"}")
        self.widget.setObjectName("widget")
        self.loginpanelLabel = QtWidgets.QLabel(self.widget)
        self.loginpanelLabel.setGeometry(QtCore.QRect(25, 25, 350, 500))
        self.loginpanelLabel.setStyleSheet("border-image: url(:/images/Assets/background.jpg);\n"
"border-radius:20px;\n"
"")
        self.loginpanelLabel.setText("")
        self.loginpanelLabel.setObjectName("loginpanelLabel")
        self.registerLabel = QtWidgets.QLabel(self.widget)
        self.registerLabel.setGeometry(QtCore.QRect(158, 80, 85, 35))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.registerLabel.setFont(font)
        self.registerLabel.setObjectName("registerLabel")
        self.logButton = QtWidgets.QPushButton(self.widget)
        self.logButton.setGeometry(QtCore.QRect(100, 370, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logButton.setFont(font)
        self.logButton.setObjectName("logButton")
        self.githubButton = QtWidgets.QPushButton(self.widget)
        self.githubButton.setGeometry(QtCore.QRect(310, 460, 40, 40))
        self.githubButton.setStyleSheet("border-image: url(:/images/github-mark-white.png);\n"
"border-radius:20px;")
        self.githubButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Assets/github-mark-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.githubButton.setIcon(icon)
        self.githubButton.setIconSize(QtCore.QSize(32, 32))
        self.githubButton.setObjectName("githubButton")
        self.remCheckBox = QtWidgets.QCheckBox(self.widget)
        self.remCheckBox.setGeometry(QtCore.QRect(100, 420, 116, 21))
        self.remCheckBox.setObjectName("remCheckBox")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(140, 190, 75, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(150, 290, 71, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Form"))
        self.registerLabel.setText(_translate("LoginWindow", "Login"))
        self.logButton.setText(_translate("LoginWindow", "Login"))
        self.remCheckBox.setText(_translate("LoginWindow", "Remember me"))
        self.label.setText(_translate("LoginWindow", "Keystore file"))
        self.label_2.setText(_translate("LoginWindow", "Account file"))
